apiVersion: v1
kind: Pod
metadata:
  name: audit-mode
  labels:
    app: audit-mode
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/audit.json
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
