apiVersion: v1
kind: Pod
metadata:
  name: default-mode
  labels:
    app: default-mode
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
